/*
 * Output.java
 *
 * Created on __DATE__, __TIME__
 */

package assemParsing;


/**
 *
 * @author  __USER__
 */
public class Output extends javax.swing.JFrame {

	/** Creates new form Output */
	public Output() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("jButton1");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(46, 46, 46)
						.addComponent(jButton1)
						.addContainerGap(273, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(46, 46, 46)
						.addComponent(jButton1)
						.addContainerGap(226, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		ParseTest pt = new ParseTest();
		// SIC 명령어 파일을 읽어 들이기 위한 초기화 작업을 수행한다.
		pt.initialize();
		
		// 읽어드린 내용을 Vector 클래스를 활용하여 Parsing 한다.
		pt.parseData(pt.fp);
		
		// Parsing 된 내용을 정해진 파일명으로 출력한다.
		pt.printOPCODE();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Output().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables

}